bookstore/bookstore/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^.*', include('main.urls')),
]

bookstore/main/urls.py
from django.conf.urls import url
from main import views


urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^contact/$', views.contact, name='contact'),
]

bookstore/main/models.py
from django.db import models

# Create your models here.

bookstore/main/views.py
from django.shortcuts import render
import datetime


def main(request):
    '''
    Show 'Hello world!' in the main page
    '''
    context = {'now':int(datetime.datetime.now().strftime("%H"))}
    return render(request, 'main/main.html', context)

def contact(request):
    '''
    Render the contact page
    '''
    return render(request, 'main/contact.html')

bookstore/main/templates/main/contact.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>聯絡我們</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    <h2>聯絡我們</h2>
  </body>
</html>

bookstore/main/templates/main/main.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>書局</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    <h2>歡迎光臨本書店</h2>
    <p>{{ now }}</p>
    {% if now < 12 %}
      <P>早安</P>
    {% else %}
      <P>午安</P>
    {% endif %}
    <img src="../../static/main/img/0.jpg" alt="book">
  </body>
</html>

bookstore/main/templates/main/menu.html
<ul id="menu">
      <li><a href="{% url 'main:main' %}">首頁</a></li>
      <li><a href="{% url 'main:contact' %}">聯絡我們</a></li>
    </ul>